 // === BIBLE DATA ===
        const bibleBooks = [
            // OLD TESTAMENT
            { id: 'genesis', title: 'Genesis', chapters: 50, testament: 'old', emoji: '🌱', description: 'The beginning of everything' },
            { id: 'exodus', title: 'Exodus', chapters: 40, testament: 'old', emoji: '⛰️', description: 'Freedom from slavery' },
            { id: 'leviticus', title: 'Leviticus', chapters: 27, testament: 'old', emoji: '🕊️', description: 'Laws and worship' },
            { id: 'numbers', title: 'Numbers', chapters: 36, testament: 'old', emoji: '🏜️', description: 'Wilderness journey' },
            { id: 'deuteronomy', title: 'Deuteronomy', chapters: 34, testament: 'old', emoji: '📜', description: 'Moses final words' },
            
            { id: 'joshua', title: 'Joshua', chapters: 24, testament: 'old', emoji: '⚔️', description: 'Conquering the promised land' },
            { id: 'judges', title: 'Judges', chapters: 21, testament: 'old', emoji: '👨‍⚖️', description: 'Leaders before kings' },
            { id: 'ruth', title: 'Ruth', chapters: 4, testament: 'old', emoji: '💝', description: 'Loyalty and love story' },
            { id: '1samuel', title: '1 Samuel', chapters: 31, testament: 'old', emoji: '👑', description: 'First kings of Israel' },
            { id: '2samuel', title: '2 Samuel', chapters: 24, testament: 'old', emoji: '🛡️', description: 'King David reign' },
            { id: '1kings', title: '1 Kings', chapters: 22, testament: 'old', emoji: '🏰', description: 'Solomon and division' },
            { id: '2kings', title: '2 Kings', chapters: 25, testament: 'old', emoji: '💔', description: 'Fall of kingdoms' },
            { id: '1chronicles', title: '1 Chronicles', chapters: 29, testament: 'old', emoji: '📚', description: 'History retold' },
            { id: '2chronicles', title: '2 Chronicles', chapters: 36, testament: 'old', emoji: '🏛️', description: 'Temple and kings' },
            { id: 'ezra', title: 'Ezra', chapters: 10, testament: 'old', emoji: '🔨', description: 'Rebuilding after exile' },
            { id: 'nehemiah', title: 'Nehemiah', chapters: 13, testament: 'old', emoji: '🧱', description: 'Rebuilding walls' },
            { id: 'esther', title: 'Esther', chapters: 10, testament: 'old', emoji: '👸', description: 'Courage saves a nation' },
            
            { id: 'job', title: 'Job', chapters: 42, testament: 'old', emoji: '💪', description: 'Suffering and faith' },
            { id: 'psalms', title: 'Psalms', chapters: 150, testament: 'old', emoji: '🎵', description: 'Songs of worship' },
            { id: 'proverbs', title: 'Proverbs', chapters: 31, testament: 'old', emoji: '💎', description: 'Wisdom for life' },
            { id: 'ecclesiastes', title: 'Ecclesiastes', chapters: 12, testament: 'old', emoji: '🤔', description: 'Meaning of life' },
            { id: 'songofsolomon', title: 'Song of Solomon', chapters: 8, testament: 'old', emoji: '🌹', description: 'Love poetry' },
            
            { id: 'isaiah', title: 'Isaiah', chapters: 66, testament: 'old', emoji: '🔥', description: 'Prophecy and hope' },
            { id: 'jeremiah', title: 'Jeremiah', chapters: 52, testament: 'old', emoji: '😢', description: 'Tears and warnings' },
            { id: 'lamentations', title: 'Lamentations', chapters: 5, testament: 'old', emoji: '💧', description: 'Mourning destruction' },
            { id: 'ezekiel', title: 'Ezekiel', chapters: 48, testament: 'old', emoji: '👁️', description: 'Visions and restoration' },
            { id: 'daniel', title: 'Daniel', chapters: 12, testament: 'old', emoji: '🦁', description: 'Faith in exile' },
            
            { id: 'hosea', title: 'Hosea', chapters: 14, testament: 'old', emoji: '💔', description: 'Unfaithful love' },
            { id: 'joel', title: 'Joel', chapters: 3, testament: 'old', emoji: '🦗', description: 'Locust plague prophecy' },
            { id: 'amos', title: 'Amos', chapters: 9, testament: 'old', emoji: '⚖️', description: 'Justice for the poor' },
            { id: 'obadiah', title: 'Obadiah', chapters: 1, testament: 'old', emoji: '⚡', description: 'Judgment on Edom' },
            { id: 'jonah', title: 'Jonah', chapters: 4, testament: 'old', emoji: '🐋', description: 'Running from God' },
            { id: 'micah', title: 'Micah', chapters: 7, testament: 'old', emoji: '🏔️', description: 'Justice and mercy' },
            { id: 'nahum', title: 'Nahum', chapters: 3, testament: 'old', emoji: '💥', description: 'Nineveh judgment' },
            { id: 'habakkuk', title: 'Habakkuk', chapters: 3, testament: 'old', emoji: '❓', description: 'Questions to God' },
            { id: 'zephaniah', title: 'Zephaniah', chapters: 3, testament: 'old', emoji: '🌪️', description: 'Day of the Lord' },
            { id: 'haggai', title: 'Haggai', chapters: 2, testament: 'old', emoji: '🏗️', description: 'Rebuild the temple' },
            { id: 'zechariah', title: 'Zechariah', chapters: 14, testament: 'old', emoji: '🕊️', description: 'Visions of hope' },
            { id: 'malachi', title: 'Malachi', chapters: 4, testament: 'old', emoji: '🔚', description: 'Final OT message' },
            
            // NEW TESTAMENT
            { id: 'matthew', title: 'Matthew', chapters: 28, testament: 'new', emoji: '👑', description: 'Jesus the King' },
            { id: 'mark', title: 'Mark', chapters: 16, testament: 'new', emoji: '🏃', description: 'Jesus in action' },
            { id: 'luke', title: 'Luke', chapters: 24, testament: 'new', emoji: '🩺', description: 'Jesus the healer' },
            { id: 'john', title: 'John', chapters: 21, testament: 'new', emoji: '❤️', description: 'Jesus the beloved' },
            { id: 'acts', title: 'Acts', chapters: 28, testament: 'new', emoji: '🔥', description: 'Early church power' },
            { id: 'romans', title: 'Romans', chapters: 16, testament: 'new', emoji: '⚖️', description: 'Gospel foundation' },
            { id: '1corinthians', title: '1 Corinthians', chapters: 16, testament: 'new', emoji: '🤝', description: 'Church unity' },
            { id: '2corinthians', title: '2 Corinthians', chapters: 13, testament: 'new', emoji: '💪', description: 'Strength in weakness' },
            { id: 'galatians', title: 'Galatians', chapters: 6, testament: 'new', emoji: '🆓', description: 'Freedom in Christ' },
            { id: 'ephesians', title: 'Ephesians', chapters: 6, testament: 'new', emoji: '🛡️', description: 'Spiritual armor' },
            { id: 'philippians', title: 'Philippians', chapters: 4, testament: 'new', emoji: '😊', description: 'Joy in Christ' },
            { id: 'colossians', title: 'Colossians', chapters: 4, testament: 'new', emoji: '🌟', description: 'Christ supreme' },
            { id: '1thessalonians', title: '1 Thessalonians', chapters: 5, testament: 'new', emoji: '🙌', description: 'Living for Jesus' },
            { id: '2thessalonians', title: '2 Thessalonians', chapters: 3, testament: 'new', emoji: '⏰', description: 'Second coming' },
            { id: '1timothy', title: '1 Timothy', chapters: 6, testament: 'new', emoji: '👨‍🏫', description: 'Church leadership' },
            { id: '2timothy', title: '2 Timothy', chapters: 4, testament: 'new', emoji: '🔥', description: 'Finishing strong' },
            { id: 'titus', title: 'Titus', chapters: 3, testament: 'new', emoji: '🏗️', description: 'Church organization' },
            { id: 'philemon', title: 'Philemon', chapters: 1, testament: 'new', emoji: '🤗', description: 'Forgiveness letter' },
            { id: 'hebrews', title: 'Hebrews', chapters: 13, testament: 'new', emoji: '⛪', description: 'Jesus our high priest' },
            { id: 'james', title: 'James', chapters: 5, testament: 'new', emoji: '🌱', description: 'Faith in action' },
            { id: '1peter', title: '1 Peter', chapters: 5, testament: 'new', emoji: '🗿', description: 'Hope in suffering' },
            { id: '2peter', title: '2 Peter', chapters: 3, testament: 'new', emoji: '📚', description: 'Growing in faith' },
            { id: '1john', title: '1 John', chapters: 5, testament: 'new', emoji: '💕', description: 'God is love' },
            { id: '2john', title: '2 John', chapters: 1, testament: 'new', emoji: '💌', description: 'Love and truth' },
            { id: '3john', title: '3 John', chapters: 1, testament: 'new', emoji: '🤝', description: 'Hospitality matters' },
            { id: 'jude', title: 'Jude', chapters: 1, testament: 'new', emoji: '⚔️', description: 'Fight for faith' },
            { id: 'revelation', title: 'Revelation', chapters: 22, testament: 'new', emoji: '🔮', description: 'Ultimate victory' }
            ];