// Bible or Cap Game Data - 100+ Statements
const capStatements = [
    // REAL Bible verses (60 real ones)
    { text: "A man's stomach shall be satisfied from the fruit of his mouth.", isReal: true, reference: "Proverbs 18:20" },
    { text: "Iron sharpens iron, and one man sharpens another.", isReal: true, reference: "Proverbs 27:17" },
    { text: "The Lord is my shepherd; I shall not want.", isReal: true, reference: "Psalm 23:1" },
    { text: "Jesus wept.", isReal: true, reference: "John 11:35" },
    { text: "Love is patient, love is kind.", isReal: true, reference: "1 Corinthians 13:4" },
    { text: "In the beginning was the Word, and the Word was with God.", isReal: true, reference: "John 1:1" },
    { text: "The fear of the Lord is the beginning of wisdom.", isReal: true, reference: "Proverbs 9:10" },
    { text: "Where two or three gather in my name, there am I with them.", isReal: true, reference: "Matthew 18:20" },
    { text: "Greater love has no one than this: to lay down one's life for one's friends.", isReal: true, reference: "John 15:13" },
    { text: "Do not worry about tomorrow, for tomorrow will worry about itself.", isReal: true, reference: "Matthew 6:34" },
    { text: "The Lord gave, and the Lord has taken away; blessed be the name of the Lord.", isReal: true, reference: "Job 1:21" },
    { text: "Be still, and know that I am God.", isReal: true, reference: "Psalm 46:10" },
    { text: "The righteous person may have many troubles, but the Lord delivers him from them all.", isReal: true, reference: "Psalm 34:19" },
    { text: "A gentle answer turns away wrath, but a harsh word stirs up anger.", isReal: true, reference: "Proverbs 15:1" },
    { text: "Trust in the Lord with all your heart and lean not on your own understanding.", isReal: true, reference: "Proverbs 3:5" },
    { text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you.", isReal: true, reference: "Jeremiah 29:11" },
    { text: "I can do all things through Christ who strengthens me.", isReal: true, reference: "Philippians 4:13" },
    { text: "The wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", isReal: true, reference: "Romans 6:23" },
    { text: "For God so loved the world that he gave his one and only Son.", isReal: true, reference: "John 3:16" },
    { text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.", isReal: true, reference: "Matthew 7:7" },
    { text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", isReal: true, reference: "Psalm 34:18" },
    { text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", isReal: true, reference: "Romans 12:2" },
    { text: "Come to me, all you who are weary and burdened, and I will give you rest.", isReal: true, reference: "Matthew 11:28" },
    { text: "Cast all your anxiety on him because he cares for you.", isReal: true, reference: "1 Peter 5:7" },
    { text: "The Lord is my light and my salvation—whom shall I fear?", isReal: true, reference: "Psalm 27:1" },
    { text: "No weapon forged against you will prevail.", isReal: true, reference: "Isaiah 54:17" },
    { text: "If God is for us, who can be against us?", isReal: true, reference: "Romans 8:31" },
    { text: "The joy of the Lord is your strength.", isReal: true, reference: "Nehemiah 8:10" },
    { text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles.", isReal: true, reference: "Isaiah 40:31" },
    { text: "Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God.", isReal: true, reference: "Philippians 4:6" },
    { text: "The Lord will fight for you; you need only to be still.", isReal: true, reference: "Exodus 14:14" },
    { text: "Taste and see that the Lord is good; blessed is the one who takes refuge in him.", isReal: true, reference: "Psalm 34:8" },
    { text: "Whatever you do, work at it with all your heart, as working for the Lord.", isReal: true, reference: "Colossians 3:23" },
    { text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you.", isReal: true, reference: "Joshua 1:9" },
    { text: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", isReal: true, reference: "Matthew 5:16" },
    { text: "The Lord bless you and keep you; the Lord make his face shine on you.", isReal: true, reference: "Numbers 6:24-25" },
    { text: "He heals the brokenhearted and binds up their wounds.", isReal: true, reference: "Psalm 147:3" },
    { text: "And we know that in all things God works for the good of those who love him.", isReal: true, reference: "Romans 8:28" },
    { text: "The Lord is gracious and compassionate, slow to anger and rich in love.", isReal: true, reference: "Psalm 145:8" },
    { text: "Do not be overcome by evil, but overcome evil with good.", isReal: true, reference: "Romans 12:21" },
    { text: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.", isReal: true, reference: "James 4:7" },
    { text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", isReal: true, reference: "2 Corinthians 5:17" },
    { text: "Above all, love each other deeply, because love covers over a multitude of sins.", isReal: true, reference: "1 Peter 4:8" },
    { text: "Blessed are the pure in heart, for they will see God.", isReal: true, reference: "Matthew 5:8" },
    { text: "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.", isReal: true, reference: "1 Thessalonians 5:18" },
    { text: "The grass withers and the flowers fall, but the word of our God endures forever.", isReal: true, reference: "Isaiah 40:8" },
    { text: "Surely your goodness and love will follow me all the days of my life.", isReal: true, reference: "Psalm 23:6" },
    { text: "Do not let your hearts be troubled. You believe in God; believe also in me.", isReal: true, reference: "John 14:1" },
    { text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives.", isReal: true, reference: "John 14:27" },
    { text: "For where two or three gather in my name, there am I with them.", isReal: true, reference: "Matthew 18:20" },
    { text: "The Lord is my rock, my fortress and my deliverer.", isReal: true, reference: "Psalm 18:2" },
    { text: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", isReal: true, reference: "Ephesians 4:32" },
    { text: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, think about such things.", isReal: true, reference: "Philippians 4:8" },
    { text: "The tongue has the power of life and death.", isReal: true, reference: "Proverbs 18:21" },
    { text: "Humble yourselves before the Lord, and he will lift you up.", isReal: true, reference: "James 4:10" },
    { text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", isReal: true, reference: "Matthew 6:33" },
    { text: "My grace is sufficient for you, for my power is made perfect in weakness.", isReal: true, reference: "2 Corinthians 12:9" },
    { text: "Train up a child in the way he should go; even when he is old he will not depart from it.", isReal: true, reference: "Proverbs 22:6" },
    { text: "Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion.", isReal: true, reference: "1 Peter 5:8" },
    { text: "Rejoice always, pray continually, give thanks in all circumstances.", isReal: true, reference: "1 Thessalonians 5:16-18" },
    
    // FAKE verses (Cap!) - 50 fake ones
    { text: "Blessed are those who help themselves, for they shall prosper.", isReal: false, reference: "NOT IN BIBLE" },
    { text: "God works in mysterious ways.", isReal: false, reference: "NOT IN BIBLE (Common saying but not Scripture)" },
    { text: "Cleanliness is next to godliness.", isReal: false, reference: "NOT IN BIBLE (John Wesley quote)" },
    { text: "Money is the root of all evil.", isReal: false, reference: "NOT IN BIBLE (1 Tim 6:10 says 'LOVE of money')" },
    { text: "This too shall pass.", isReal: false, reference: "NOT IN BIBLE (Persian proverb)" },
    { text: "God helps those who help themselves.", isReal: false, reference: "NOT IN BIBLE (Ben Franklin)" },
    { text: "To thine own self be true.", isReal: false, reference: "Shakespeare (Hamlet), not Bible!" },
    { text: "Spare the rod, spoil the child.", isReal: false, reference: "NOT IN BIBLE (Proverbs 13:24 is similar but different)" },
    { text: "The Lord moves in mysterious ways.", isReal: false, reference: "NOT IN BIBLE (William Cowper poem)" },
    { text: "Hate the sin, love the sinner.", isReal: false, reference: "NOT IN BIBLE (St. Augustine)" },
    { text: "God will never give you more than you can handle.", isReal: false, reference: "NOT IN BIBLE (1 Cor 10:13 is about temptation only)" },
    { text: "Everything happens for a reason.", isReal: false, reference: "NOT IN BIBLE (Popular phrase)" },
    { text: "The lion shall lie down with the lamb.", isReal: false, reference: "NOT IN BIBLE (Isaiah 11:6 says 'wolf with lamb')" },
    { text: "Pride comes before the fall.", isReal: false, reference: "NOT IN BIBLE (Prov 16:18 says 'before destruction')" },
    { text: "An eye for an eye makes the whole world blind.", isReal: false, reference: "Gandhi, not Bible!" },
    { text: "God won't give you anything you can't handle.", isReal: false, reference: "NOT IN BIBLE (Misquote)" },
    { text: "When God closes a door, He opens a window.", isReal: false, reference: "NOT IN BIBLE (Popular saying)" },
    { text: "Let go and let God.", isReal: false, reference: "NOT IN BIBLE (AA slogan)" },
    { text: "The early bird gets the worm.", isReal: false, reference: "Proverb, NOT Bible!" },
    { text: "A penny saved is a penny earned.", isReal: false, reference: "Ben Franklin, not Bible!" },
    { text: "Honesty is the best policy.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "What doesn't kill you makes you stronger.", isReal: false, reference: "Nietzsche, not Bible!" },
    { text: "Charity begins at home.", isReal: false, reference: "NOT IN BIBLE (Sir Thomas Browne)" },
    { text: "All roads lead to heaven.", isReal: false, reference: "NOT IN BIBLE (Contradicts John 14:6)" },
    { text: "We are all God's children.", isReal: false, reference: "NOT IN BIBLE (Only believers are called children of God)" },
    { text: "Once saved, always saved.", isReal: false, reference: "NOT IN BIBLE (Theological debate, not a verse)" },
    { text: "Forgive and forget.", isReal: false, reference: "NOT IN BIBLE (Bible says forgive, not forget)" },
    { text: "God only helps those who are faithful.", isReal: false, reference: "NOT IN BIBLE (God helps sinners too!)" },
    { text: "The bigger they are, the harder they fall.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "Beauty is only skin deep.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Home is where the heart is.", isReal: false, reference: "NOT IN BIBLE (Pliny the Elder)" },
    { text: "Better late than never.", isReal: false, reference: "NOT IN BIBLE (Ancient proverb)" },
    { text: "Actions speak louder than words.", isReal: false, reference: "NOT IN BIBLE (Abraham Lincoln)" },
    { text: "You reap what you sow.", isReal: true, reference: "Galatians 6:7" },
    { text: "Two wrongs don't make a right.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "When in Rome, do as the Romans do.", isReal: false, reference: "St. Augustine (not Bible!)" },
    { text: "Practice makes perfect.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "Laughter is the best medicine.", isReal: false, reference: "NOT IN BIBLE (Proverbs 17:22 is similar)" },
    { text: "Blood is thicker than water.", isReal: false, reference: "NOT IN BIBLE (Medieval proverb)" },
    { text: "The proof is in the pudding.", isReal: false, reference: "NOT IN BIBLE (Old English proverb)" },
    { text: "You can't teach an old dog new tricks.", isReal: false, reference: "NOT IN BIBLE (Common saying)" },
    { text: "Birds of a feather flock together.", isReal: false, reference: "NOT IN BIBLE (English proverb)" },
    { text: "Where there's smoke, there's fire.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Don't count your chickens before they hatch.", isReal: false, reference: "NOT IN BIBLE (Aesop's Fables)" },
    { text: "A watched pot never boils.", isReal: false, reference: "NOT IN BIBLE (Benjamin Franklin)" },
    { text: "Fool me once, shame on you; fool me twice, shame on me.", isReal: false, reference: "NOT IN BIBLE (Proverb)" },
    { text: "Time heals all wounds.", isReal: false, reference: "NOT IN BIBLE (Ancient saying)" },
    { text: "Silence is golden.", isReal: false, reference: "NOT IN BIBLE (Ancient proverb)" },
    { text: "The best things in life are free.", isReal: false, reference: "NOT IN BIBLE (Song lyric)" },
    { text: "What goes around comes around.", isReal: false, reference: "NOT IN BIBLE (Karma concept)" },
];
